bench_name: autocodearena

# a list of model to generate answers
model_list:
  - gpt-4o-mini-2024-07-18
  # - gpt-4o-2024-11-20
  # - claude35_sonnet
  # - claude35_haiku
  # - gemini-2.5-pro
  # - gemini-2.5-flash
  # - qwen3-coder
  # - claude37_sonnet
  # - gpt-oss-120b
  # - gpt-oss-20b
  # - deepseek-chat-v3-0324
  # - glm-4.5
  # - gpt-4.1-2025-04-14
  # - kimi-k2
  # - o4-mini-2025-04-16
  # - o3-mini-2025-01-31
  # - deepseek-r1-0528
  # - gpt-5-2025-08-07
  # - claude-4-sonnet
  # - claude-4-opus
  # - deepseek-chat-v3.1
  # - grok-code